// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0
// source: post.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const countPosts = `-- name: CountPosts :one
SELECT COUNT(*) FROM posts
`

func (q *Queries) CountPosts(ctx context.Context) (int64, error) {
	row := q.queryRow(ctx, q.countPostsStmt, countPosts)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPost = `-- name: CreatePost :one
INSERT INTO posts (
  title,
  content,
  category,
  image
) VALUES (
  $1, $2, $3, $4
)
RETURNING id, title, category, content, image, created_at, updated_at, "like", dislike
`

type CreatePostParams struct {
	Title    string `json:"title"`
	Content  string `json:"content"`
	Category string `json:"category"`
	Image    string `json:"image"`
}

func (q *Queries) CreatePost(ctx context.Context, arg CreatePostParams) (Post, error) {
	row := q.queryRow(ctx, q.createPostStmt, createPost,
		arg.Title,
		arg.Content,
		arg.Category,
		arg.Image,
	)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Category,
		&i.Content,
		&i.Image,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Like,
		&i.Dislike,
	)
	return i, err
}

const deletePost = `-- name: DeletePost :exec
DELETE FROM posts
WHERE id = $1
`

func (q *Queries) DeletePost(ctx context.Context, id uuid.UUID) error {
	_, err := q.exec(ctx, q.deletePostStmt, deletePost, id)
	return err
}

const dislikePost = `-- name: DislikePost :exec
UPDATE posts
set
"dislike" = "dislike" + 1
WHERE id = $1
`

func (q *Queries) DislikePost(ctx context.Context, id uuid.UUID) error {
	_, err := q.exec(ctx, q.dislikePostStmt, dislikePost, id)
	return err
}

const getDislike = `-- name: GetDislike :one
SELECT "dislike" FROM posts
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetDislike(ctx context.Context, id uuid.UUID) (int32, error) {
	row := q.queryRow(ctx, q.getDislikeStmt, getDislike, id)
	var dislike int32
	err := row.Scan(&dislike)
	return dislike, err
}

const getLike = `-- name: GetLike :one
SELECT "like" FROM posts
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetLike(ctx context.Context, id uuid.UUID) (int32, error) {
	row := q.queryRow(ctx, q.getLikeStmt, getLike, id)
	var like int32
	err := row.Scan(&like)
	return like, err
}

const getPostById = `-- name: GetPostById :one
SELECT id, title, category, content, image, created_at, updated_at, "like", dislike FROM posts
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetPostById(ctx context.Context, id uuid.UUID) (Post, error) {
	row := q.queryRow(ctx, q.getPostByIdStmt, getPostById, id)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Category,
		&i.Content,
		&i.Image,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Like,
		&i.Dislike,
	)
	return i, err
}

const likePost = `-- name: LikePost :exec
UPDATE posts
set
"like" = "like" + 1
WHERE id = $1
`

func (q *Queries) LikePost(ctx context.Context, id uuid.UUID) error {
	_, err := q.exec(ctx, q.likePostStmt, likePost, id)
	return err
}

const listPosts = `-- name: ListPosts :many
SELECT id, title, category, content, image, created_at, updated_at, "like", dislike FROM posts
ORDER BY id
LIMIT $1
OFFSET $2
`

type ListPostsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListPosts(ctx context.Context, arg ListPostsParams) ([]Post, error) {
	rows, err := q.query(ctx, q.listPostsStmt, listPosts, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Post
	for rows.Next() {
		var i Post
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Category,
			&i.Content,
			&i.Image,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Like,
			&i.Dislike,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePost = `-- name: UpdatePost :one
UPDATE posts
set 
title = coalesce($1, title), 
category = coalesce($2, category), 
content = coalesce($3, content) ,
image = coalesce($4, image), 
updated_at = coalesce($5, updated_at ) 
WHERE id = $6
RETURNING id, title, category, content, image, created_at, updated_at, "like", dislike
`

type UpdatePostParams struct {
	Title     sql.NullString `json:"title"`
	Category  sql.NullString `json:"category"`
	Content   sql.NullString `json:"content"`
	Image     sql.NullString `json:"image"`
	UpdatedAt sql.NullTime   `json:"updated_at "`
	ID        uuid.UUID      `json:"id"`
}

func (q *Queries) UpdatePost(ctx context.Context, arg UpdatePostParams) (Post, error) {
	row := q.queryRow(ctx, q.updatePostStmt, updatePost,
		arg.Title,
		arg.Category,
		arg.Content,
		arg.Image,
		arg.UpdatedAt,
		arg.ID,
	)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Category,
		&i.Content,
		&i.Image,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Like,
		&i.Dislike,
	)
	return i, err
}
